api_platform:
    title: 'Bagheera API'
    formats:
        json: ['application/json']
        jsonapi: ['application/vnd.api+json']
        html: ['text/html']
    error_formats:
        jsonapi: ['application/vnd.api+json']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    enable_re_doc: false
    show_webby: false
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
