parameters:
    env(DATABASE_URL): ''
    env(DATABASE_SECURE_URL): ''

doctrine:
    dbal:
        connections:
            default:
                driver: pdo_pgsql
                charset: UTF8
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '9.4'
                override_url: true
            secure:
                driver: pdo_pgsql
                charset: UTF8
                url: '%env(resolve:DATABASE_SECURE_URL)%'
                server_version: '9.4'
                override_url: true

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
            secure:
                connection: secure
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
