php_version: 7.3

pre_composer_script: |
  #!/bin/bash
  echo 'APP_SECRET=4d60fc8c3bdfdcb343c262a660db520f
  POSTGRES_HOST=bagheera-postgresql
  POSTGRES_DB=bagheera
  POSTGRES_USER=bagheera
  POSTGRES_PASSWORD=bagheera
  POSTGRES_SECURE_HOST=bagheera-postgresql
  POSTGRES_SECURE_DB=bagheera
  POSTGRES_SECURE_USER=bagheera
  POSTGRES_SECURE_PASSWORD=bagheera' > .env.test
