php_version: 7.3

pre_composer_script: |
  #!/bin/bash
  sed -i -e "s/APP_SECRET=/APP_SECRET=4d60fc8c3bdfdcb343c262a660db520f/" .env
  sed -i -e "s/^DATABASE_URL=.*/DATABASE_URL=null/" .env
  sed -i -e "s/^DATABASE_SECURE_URL=.*/DATABASE_SECURE_URL=null/" .env

global_exclude_dirs:
  - .ansible
  - .docker
  - tests
  - var
  - vendor

rules:
  web.missing_robots_txt:
    enabled: false
  web.missing_web_manifest:
    enabled: false
