language: minimal

services:
  - docker

before_install:
  - cp docker/.docker-compose.env.dist docker/.docker-compose.env
  - echo 'APP_SECRET=4d60fc8c3bdfdcb343c262a660db520f' >> docker/.docker-compose.env
  - ./bin/docker-start

script:
  - ./vendor/bin/phpstan analyse
  - ./bin/docker-test --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
