language: minimal

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.27.4
    - APP_ENV=dev
    - NODE_ENV=development

before_install:
  - curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o bin/php-cs-fixer && chmod a+x bin/php-cs-fixer
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o docker-compose
  - sudo install --mode=775 docker-compose /usr/local/bin
  - cp .docker/.docker-compose.env.dist .docker/.docker-compose.env
  - echo 'APP_SECRET=4d60fc8c3bdfdcb343c262a660db520f' >> .docker/.docker-compose.env
  - make docker-start
  - make docker-exec COMMAND="make build"

script:
  - make docker-test-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
