base:
  build: .
  dockerfile: ./app/Resources/config/docker/base/Dockerfile
  volumes:
    - .:/srv/www/bagheera

postgresqldata:
  image: bagheera_base
  environment:
    - ENV=dev
  volumes:
    - /var/lib/postgresql
  volumes_from:
    - base

postgresql:
  build: ./app/Resources/config/docker/postgresql
  restart: always
  env_file: .docker-compose.env
  environment:
    - ENV=dev
  volumes_from:
    - base
    - postgresqldata

php:
  build: ./app/Resources/config/docker/php
  restart: always
  env_file: .docker-compose.env
  environment:
    - ENV=dev
  volumes_from:
    - base
  links:
    - postgresql

nginx:
  build: ./app/Resources/config/docker/nginx
  restart: always
  environment:
    - ENV=dev
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - base
  links:
    - php
