- hosts: all
  remote_user: root
  sudo: yes
  vars_files:
    - vault.yml
  vars:
    - project_dir: /srv/www/bagheera
  tasks:
    - name: Add jessie-backports repository
      apt_repository: repo='deb http://ftp.fr.debian.org/debian jessie-backports main contrib non-free'
    - name: Add jessie-backports src repository
      apt_repository: repo='deb-src http://ftp.fr.debian.org/debian jessie-backports main contrib non-free'
    - name: Download Docker package
      get_url: url=http://downloads.hypriot.com/docker-hypriot_1.8.3-1_armhf.deb dest=/tmp/docker-hypriot_1.8.3-1_armhf.deb
    - name: Install Docker
      apt: deb=/tmp/docker-hypriot_1.8.3-1_armhf.deb
    - name: Reload some Docker configuration
      shell: systemctl unmask docker.service && systemctl unmask docker.socket && systemctl start docker.service
    - name: Install python-setuptools
      apt: name=python-setuptools
    - name: Install easy_install
      easy_install: name=pip
    - name: Install docker-py
      pip: name=docker-py==1.4.0
    - name: Install docker-compose
      pip: name=docker-compose
    - name: Fetch project sources
      git: repo=git@bitbucket.org:krevindiou/bagheera.git
        accept_hostkey=yes
        dest={{ project_dir }}
    - name: Create Docker env file
      command: cp {{ project_dir }}/.docker-compose.env.dist {{ project_dir }}/.docker-compose.env
    - name: Set database password
      replace: dest={{ project_dir }}/.docker-compose.env
        regexp='^(DATABASE_PASSWORD=).*$'
        replace='\1{{ database_password }}'
    - name: Set secure database password
      replace: dest={{ project_dir }}/.docker-compose.env
        regexp='^(DATABASE_SECURE_PASSWORD=).*$'
        replace='\1{{ database_secure_password }}'
    - name: Create Docker images
      command: '{{ project_dir }}/bin/start prod'
