imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en
    email:
        sender_name: Bagheera
        sender_email: contact@bagheera-manager.com
    categories_id:
        salary: 21

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: BAGHEERA_SESS_ID
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'AppBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles:
        - AppBundle
    filters:
        cssrewrite:
            apply_to: '\.(less|css)$'
        less:
            node: /usr/bin/node
            node_paths: ['%kernel.root_dir%/Resources/node_modules']
            apply_to: '\.less$'
        uglifyjs2:
            bin: '%kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs'
            apply_to: '\.js$'
        uglifycss:
            bin: '%kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss'
            apply_to: '\.less$'

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver: pdo_pgsql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
            secure:
                driver: pdo_pgsql
                host: '%database_secure_host%'
                port: '%database_secure_port%'
                dbname: '%database_secure_name%'
                user: '%database_secure_user%'
                password: '%database_secure_password%'
                charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle: ~
            secure:
                connection: secure
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBundle]
