imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name:            BAGHEERA_SESS_ID
        cookie_lifetime: ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'KrevindiouBagheeraBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - KrevindiouBagheeraBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            secure:
                driver:   %database_secure_driver%
                host:     %database_secure_host%
                port:     %database_secure_port%
                dbname:   %database_secure_name%
                user:     %database_secure_user%
                password: %database_secure_password%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    KrevindiouBagheeraBundle:
                        mapping:              true
                        type:                 ~
                        dir:                  ~
                        alias:                Model
                        prefix:               ~
                        is_bundle:            ~
            secure:
                connection:       secure
                mappings:
                    KrevindiouBagheeraBundle:
                        mapping:              true
                        type:                 ~
                        dir:                  ~
                        alias:                Model
                        prefix:               ~
                        is_bundle:            ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

jms_di_extra:
    locations:
        all_bundles: true

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

parameters:
    email:
        sender_name:    Bagheera
        sender_email:   contact@bagheera-manager.com
    providers:
        axa_banque:
            base_uri:       %provider_axa_banque_base_uri%
            client_id:      %provider_axa_banque_client_id%
            access_token:   %provider_axa_banque_access_token%
