KrevindiouBagheeraBundle:
    resource: "@KrevindiouBagheeraBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: KrevindiouBagheeraBundle:User:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
