KrevindiouBagheeraBundle:
    resource: "@KrevindiouBagheeraBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: member_login
        permanent: true
