KrevindiouBagheeraBundle:
    resource: "@KrevindiouBagheeraBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: user_login
        permanent: true
