<script setup lang="ts">
import AppIcon from './AppIcon.vue';

// Small round status badge for an operation row: reconciled (a check) or
// generated by a scheduler (a clock). `data-testid` is `<kind>-icon`.
defineProps<{ kind: 'reconciled' | 'scheduler'; label: string }>();
</script>

<template>
  <span
    class="status-icon"
    :class="`status-icon-${kind}`"
    role="img"
    :title="label"
    :aria-label="label"
    :data-testid="`${kind}-icon`"
  >
    <AppIcon :name="kind === 'reconciled' ? 'check' : 'clock'" :size="12" />
  </span>
</template>

<style scoped>
.status-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  border-radius: 50%;
  vertical-align: middle;
}
/* Same "status dot" weight as .dot-active: a tinted disc behind the glyph. */
.status-icon-reconciled {
  background: rgba(95, 217, 141, 0.18);
  color: var(--green);
}
.status-icon-scheduler {
  color: var(--paper-faint);
}
</style>
