<?php

echo $this->link('newBank', $this->translate('bankNew'), array('class' => 'new'));
echo $this->link('newAccount', $this->translate('accountNew'), array('class' => 'new'));

?>

<form id="formAccountList" method="post" action="">
<?php

if (count($this->accounts) > 0) {
    echo '<ul>';

    foreach ($this->accounts as $v) {
        echo '<li>';
        echo '<input type="checkbox" name="banksId[]" value="' . $v['bank']->getBankId() . '"/>';
        echo '<strong>' . $v['bank']->getName() . '</strong>';

        if (empty($v['accounts'])) {
            echo ' - <em>' . $this->translate('noAccount'). ' </em>';
        }

        echo ' ' . $this->link('editBank', $this->translate('bankEdit'), array(), array('bankId' => $v['bank']->getBankId()));
        echo '<br/>';

        if (!empty($v['accounts'])) {
            echo '<ul>';

            foreach ($v['accounts'] as $account) {
                echo '<li>';
                echo '<input type="checkbox" name="accountsId[]" value="' . $account->getAccountId() . '"/>';
                echo $account->getName() . ' ';
                echo $this->link('editAccount', $this->translate('accountEdit'), array(), array('accountId' => $account->getAccountId()));
                echo '</li>';
            }

            echo '</ul>';
        }

        echo '</li>';
    }

    echo '</ul>';
}

?>

<div class="listActions">
    <input type="submit" name="delete" value="<?php echo $this->translate('deleteAction') ?>"/>
    <input type="submit" name="share" disabled="disabled" value="<?php echo $this->translate('shareAction') ?>"/>
</div>
</form>
