<?php if ($this->pageCount) { ?>
    <ul class="paginationControl">
    <?php
    if (isset($this->previous) && !in_array($this->first, $this->pagesInRange)) {
        echo '<li class="first">';
        echo $this->link($this->route, $this->first, array(), array('page' => $this->first));
        echo '</li>';
    }

    foreach ($this->pagesInRange as $page) {
        echo '<li>';
        if ($page != $this->current) {
            echo $this->link($this->route, $page, array(), array('page' => $page));
        } else {
            echo $page;
        }
        echo '</li>';
    }

    if (isset($this->next) && !in_array($this->last, $this->pagesInRange)) {
        echo '<li class="last">';
        echo $this->link($this->route, $this->last, array(), array('page' => $this->last));
        echo '</li>';
    }
    ?>
    </ul>
<?php } ?>
