authentication_token:
    path: /api/tokens
    methods: ['POST']

login_check:
    path: /login_check

logout:
    path: /logout

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: member_login

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
