parameters:
    locale: 'en'
    email:
        sender_name: Bagheera
        sender_email: contact@bagheera-manager.com
    categories_id:
        salary: 21

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Command\ImportExternalBankCommand:
        arguments:
            $emSecure: '@doctrine.orm.secure_entity_manager'

    App\Service\BankAccessService:
        arguments:
            $secret: '%kernel.secret%'
            $emSecure: '@doctrine.orm.secure_entity_manager'

    App\Service\BankService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $environment: '%kernel.environment%'

    App\Service\MemberService:
        arguments:
            $secret: '%kernel.secret%'
            $config: '%email%'

    App\Service\OperationService:
        arguments:
            $categoriesId: '%categories_id%'

    App\Service\Provider\ProviderAdapter:
        arguments:
            $key: '%kernel.secret%'

    App\EventListener\LoginListener:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
