parameters:
    locale: 'en'
    email:
        sender_name: '%env(SENDER_NAME)%'
        sender_email: '%env(SENDER_EMAIL)%'
    categories_id:
        salary: 21

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Command\ImportExternalBankCommand:
        arguments:
            $secureEntityManager: '@doctrine.orm.secure_entity_manager'

    App\Service\BankAccessService:
        arguments:
            $secret: '%kernel.secret%'
            $secureEntityManager: '@doctrine.orm.secure_entity_manager'

    App\Service\BankService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $environment: '%kernel.environment%'

    App\Service\MemberService:
        arguments:
            $secret: '%kernel.secret%'
            $config: '%email%'

    App\Service\OperationService:
        arguments:
            $categoriesId: '%categories_id%'

    App\Service\Provider\ProviderAdapter:
        arguments:
            $key: '%kernel.secret%'
            $container: '@service_container'
