env: "{{ lookup('env', 'env')|default('dev', true) }}"
vagrant: "{{ lookup('env', 'vagrant')|default('0', true) }}"
project_dir: /srv/www/bagheera
hostname: bagheera
database_name: bagheera
database_user: bagheera
database_password: '{{ vault_database_password }}'
database_secure_name: bagheera
database_secure_user: bagheera
database_secure_password: '{{ vault_database_secure_password }}'
