<?php

echo $this->link('newTransaction', $this->translate('newTransaction'), array(), array('accountId' => $this->accountId)) . '<br/>';
echo $this->link('searchTransactions', $this->translate('searchTransactions'), array(), array('accountId' => $this->accountId)) . '<br/>';

echo '<form method="post" action="">';

if (count($this->transactions) > 0) {
    echo '<table class="data">';
    echo '<tr>';
    echo '<th></th>';
    echo '<th></th>';
    echo '<th>Third Party</th>';
    echo '<th>Category</th>';
    echo '<th>Notes</th>';
    echo '<th>Payment method</th>';
    echo '<th>Debit</th>';
    echo '<th>Credit</th>';
    echo '<th>Value date</th>';
    echo '<th></th>';
    echo '</tr>';
    foreach ($this->transactions as $transaction) {
        $scheduler = $transaction->getScheduler();

        if (!$transaction->getIsReconciled()) {
            echo '<tr class="notReconciled">';
        } else {
            echo '<tr>';
        }

        echo '<td><input type="checkbox" name="transactions[]" value="' . $transaction->getTransactionId() . '" /></td>';
        echo '<td>' . ((null !== $scheduler) ? 'scheduler' : '') . '</td>';
        echo '<td>' . $transaction->getThirdParty() . '</td>';
        echo '<td>' . $transaction->getCategory()->getName() . '</td>';
        echo '<td>' . $transaction->getNotes() . '</td>';
        echo '<td>' . $transaction->getPaymentMethod()->getName() . '</td>';
        echo '<td class="debit">' . ((0 != $transaction->getDebit()) ? $transaction->getDebit() : '') . '</td>';
        echo '<td class="credit">' . ((0 != $transaction->getCredit()) ? $transaction->getCredit() : '') . '</td>';
        echo '<td>' . $transaction->getValueDate()->format('Y-m-d') . '</td>';
        echo '<td>' . $this->link('editTransaction', $this->translate('editTransaction'), array(), array('transactionId' => $transaction->getTransactionId())) . '</td>';
        echo '</tr>';
    }
    echo '</table>';

    echo $this->paginationControl($this->transactions);
}

echo '<input type="submit" name="delete" value="Delete" />';
echo '<input type="submit" name="reconcile" value="Reconcile" />';

echo '</form>';

echo 'Balance : ' . $this->balance;
