parameters:
    krevindiou_bagheera.config:

services:
    twig.extension.bagheera:
        class: Krevindiou\BagheeraBundle\Extension\TwigExtension
        tags:
            -  { name: twig.extension }

    bagheera.user:
        class: Krevindiou\BagheeraBundle\Service\UserService
        arguments:
            - @doctrine.orm.entity_manager
            - @mailer
            - %krevindiou_bagheera.config%
            - @translator
            - @router
            - @form.factory
            - @bagheera.bank

    bagheera.bank:
        class: Krevindiou\BagheeraBundle\Service\BankService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.account

    bagheera.account:
        class: Krevindiou\BagheeraBundle\Service\AccountService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory

    bagheera.operation:
        class: Krevindiou\BagheeraBundle\Service\OperationService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory

    bagheera.scheduler:
        class: Krevindiou\BagheeraBundle\Service\SchedulerService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @bagheera.operation

    bagheera.category:
        class: Krevindiou\BagheeraBundle\Service\CategoryService
        arguments:
            - @doctrine.orm.entity_manager
