parameters:
    krevindiou_bagheera.config:

services:
    twig.extension.bagheera:
        class: Krevindiou\BagheeraBundle\Extension\TwigExtension
        tags:
            -  { name: twig.extension }

    bagheera.user:
        class: Krevindiou\BagheeraBundle\Service\UserService
        arguments:
            - @doctrine.orm.entity_manager
            - @mailer
            - %krevindiou_bagheera.config%
            - @translator
            - @router
            - @security.encoder_factory
            - @form.factory
            - @validator
            - @bagheera.bank
            - @bagheera.scheduler
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    bagheera.bank:
        class: Krevindiou\BagheeraBundle\Service\BankService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.account

    bagheera.account:
        class: Krevindiou\BagheeraBundle\Service\AccountService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator

    bagheera.operation:
        class: Krevindiou\BagheeraBundle\Service\OperationService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator

    bagheera.operation_search:
        class: Krevindiou\BagheeraBundle\Service\OperationSearchService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @service_container

    bagheera.scheduler:
        class: Krevindiou\BagheeraBundle\Service\SchedulerService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.operation

    bagheera.category:
        class: Krevindiou\BagheeraBundle\Service\CategoryService
        arguments:
            - @doctrine.orm.entity_manager

    bagheera.validator.field_exists:
        class: Krevindiou\BagheeraBundle\Constraint\FieldExistsValidator
        arguments:
            - @doctrine
        tags:
            -  { name: validator.constraint_validator, alias: bagheera.validator.field_exists }
