imports:
    - { resource: services_provider.yml }

services:
    twig.extension.bagheera:
        class: Krevindiou\BagheeraBundle\Extension\TwigExtension
        tags:
            -  { name: twig.extension }

    bagheera.user:
        class: Krevindiou\BagheeraBundle\Service\UserService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @mailer
            - %email%
            - @translator
            - @router
            - @security.encoder_factory
            - @form.factory
            - @validator
            - @bagheera.bank
            - @bagheera.scheduler
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }
            - { name: monolog.logger, channel: user }

    bagheera.bank:
        class: Krevindiou\BagheeraBundle\Service\BankService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.account
            - %kernel.root_dir%
            - %kernel.environment%
        tags:
            - { name: monolog.logger, channel: bank }

    bagheera.bank_access:
        class: Krevindiou\BagheeraBundle\Service\BankAccessService
        arguments:
            - %secret%
            - @logger
            - @doctrine.orm.entity_manager
            - @doctrine.orm.secure_entity_manager
            - @form.factory
            - @validator
            - @bagheera.bank
        tags:
            - { name: monolog.logger, channel: bank_access }

    bagheera.account:
        class: Krevindiou\BagheeraBundle\Service\AccountService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.provider_adapter
            - @bagheera.account_import
        tags:
            - { name: monolog.logger, channel: account }

    bagheera.account_import:
        class: Krevindiou\BagheeraBundle\Service\AccountImportService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager

    bagheera.operation:
        class: Krevindiou\BagheeraBundle\Service\OperationService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.account_import
        tags:
            - { name: monolog.logger, channel: operation }

    bagheera.operation_search:
        class: Krevindiou\BagheeraBundle\Service\OperationSearchService
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
            - @service_container

    bagheera.scheduler:
        class: Krevindiou\BagheeraBundle\Service\SchedulerService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @form.factory
            - @validator
            - @bagheera.operation
        tags:
            - { name: monolog.logger, channel: scheduler }

    bagheera.category:
        class: Krevindiou\BagheeraBundle\Service\CategoryService
        arguments:
            - @doctrine.orm.entity_manager

    bagheera.report:
        class: Krevindiou\BagheeraBundle\Service\ReportService
        arguments:
            - @logger
            - @doctrine.orm.entity_manager
            - @form.factory

    bagheera.provider_adapter:
        class: Krevindiou\BagheeraBundle\Service\Provider\ProviderAdapter
        arguments:
            - @doctrine.orm.entity_manager
            - %secret%
            - @bagheera.account_import
            - @service_container

    bagheera.validator.field_exists:
        class: Krevindiou\BagheeraBundle\Constraint\FieldExistsValidator
        arguments:
            - @doctrine
        tags:
            -  { name: validator.constraint_validator, alias: bagheera.validator.field_exists }
