version: "3.8"
services:
  postgresql:
    image: ghcr.io/krevindiou/bagheera-postgresql:latest
    restart: always
    volumes:
      - /srv/db/bagheera:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  php:
    image: ghcr.io/krevindiou/bagheera-php:latest
    build:
      target: prod
    restart: always
    volumes:
      - frontend:/srv/www/bagheera/public/build
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SECURE_HOST=${POSTGRES_SECURE_HOST}
      - POSTGRES_SECURE_DB=${POSTGRES_SECURE_DB}
      - POSTGRES_SECURE_USER=${POSTGRES_SECURE_USER}
      - POSTGRES_SECURE_PASSWORD=${POSTGRES_SECURE_PASSWORD}
      - APP_SECRET=${APP_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAILER_URL=${MAILER_URL}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENTRY_DSN=${SENTRY_DSN}
  nginx:
    image: ghcr.io/krevindiou/bagheera-nginx:latest
    build:
      target: prod
    restart: always
    volumes:
      - frontend:/srv/www/bagheera/public/build
    ports:
      - "8080:8080"
volumes:
  frontend:
