version: "3.8"
services:
  postgresql:
    env_file: .docker-compose.env
  php:
    env_file: .docker-compose.env
    environment:
      - APP_ENV=dev
      - NODE_ENV=development
  nginx:
    env_file: .docker-compose.env
    environment:
      - APP_ENV=dev
    ports:
      - "80:80"
