version: "3.8"
services:
  postgresql:
    container_name: bagheera-postgresql
    build:
      context: ..
      dockerfile: .docker/postgresql/Dockerfile
  php:
    container_name: bagheera-php
    build:
      context: ..
      dockerfile: .docker/php/Dockerfile
    depends_on:
      - postgresql
    environment:
      - TRUSTED_HOSTS=['^172.18.\d+.\d+$$']
  nginx:
    container_name: bagheera-nginx
    build:
      context: ..
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - php
