version: "3.8"
services:
  postgresql:
    restart: always
    volumes:
      - /srv/db/bagheera:/var/lib/postgresql/data
    environment:
      - DOCKER_ENV=prod
  php:
    restart: always
    environment:
      - DOCKER_ENV=prod
      - NODE_ENV=production
  nginx:
    restart: always
    environment:
      - DOCKER_ENV=prod
