version: "3.8"
services:
  postgresql:
    restart: always
    volumes:
      - /srv/db/bagheera:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  php:
    restart: always
    environment:
      - APP_ENV=prod
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SECURE_HOST=${POSTGRES_SECURE_HOST}
      - POSTGRES_SECURE_DB=${POSTGRES_SECURE_DB}
      - POSTGRES_SECURE_USER=${POSTGRES_SECURE_USER}
      - POSTGRES_SECURE_PASSWORD=${POSTGRES_SECURE_PASSWORD}
      - APP_SECRET=${APP_SECRET}
      - MAILER_URL=${MAILER_URL}
      - SENDER_EMAIL=${SENDER_EMAIL}
  nginx:
    restart: always
    environment:
      - APP_ENV=prod
