- name: Pull images from registry
  docker_image:
    source: pull
    name: '{{ item }}'
  with_items:
    - ghcr.io/krevindiou/bagheera-nginx:latest
    - ghcr.io/krevindiou/bagheera-postgresql:latest
    - ghcr.io/krevindiou/bagheera-php:latest

- name: Stop containers
  command: make docker-stop
  args:
    chdir: "{{ project_directory }}"

- name: Start containers
  command: make docker-start
  args:
    chdir: "{{ project_directory }}"
