- name: Stop containers
  command: make docker-stop
  args:
    chdir: "{{ project_directory }}"

- name: Start containers
  command: make docker-start
  args:
    chdir: "{{ project_directory }}"

- name: Build app
  command: make docker-exec COMMAND="make build"
  args:
    chdir: "{{ project_directory }}"
