<?php

echo $this->link('newUser', $this->translate('userNew')) . '<br/>';

echo '<form method="post" action="">';

if (count($this->users) > 0) {
    echo '<table class="data">';
    echo '<tr>';
    echo '<th></th>';
    echo '<th>' . $this->translate('userName') . '</th>';
    echo '<th>' . $this->translate('userEmail') . '</th>';
    echo '<th>' . $this->translate('userActive') . '</th>';
    echo '<th></th>';
    echo '</tr>';
    foreach ($this->users as $user) {
        echo '<tr>';
        echo '<td><input type="checkbox" name="users[]" value="' . $user->getUserId() . '" /></td>';
        echo '<td>' . $user->getFirstname() . ' ' . $user->getLastname() . '</td>';
        echo '<td>' . $user->getEmail() . '</td>';
        echo '<td class="' . ($user->getIsActive() ? 'active' : 'inactive') . '">' . ($user->getIsActive() ? 'yes' : 'no') . '</td>';
        echo '<td>' . $this->link('editUser', $this->translate('userEdit'), array(), array('userId' => $user->getUserId())) . '</td>';
        echo '</tr>';
    }
    echo '</table>';

    echo $this->paginationControl($this->users);
}

echo '<input type="submit" name="toggleDeactivation" value="' . $this->translate('userActivateDeactivateAction') . '" />';

echo '</form>';
