/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mint a CSRF token for the current session */
        get: operations["CsrfTokenController_csrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RegistrationController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProfileController_updateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProfileController_updateLocale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/profile/confirm-email-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProfileController_confirmEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SignOutController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CurrentSessionController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedulers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SchedulerController_list"];
        put?: never;
        post: operations["SchedulerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedulers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["SchedulerController_remove"];
        options?: never;
        head?: never;
        patch: operations["SchedulerController_update"];
        trace?: never;
    };
    "/schedulers/batch/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SchedulerBatchController_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OperationController_list"];
        put?: never;
        post: operations["OperationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["OperationController_update"];
        trace?: never;
    };
    "/operations/batch/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OperationBatchController_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/batch/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OperationBatchController_reconcile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OperationSearchController_recall"];
        put?: never;
        post: operations["OperationSearchController_run"];
        delete: operations["OperationSearchController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OperationAutocompleteController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/registration/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnRegistrationController_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/registration/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnRegistrationController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/authentication/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnAuthenticationController_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/authentication/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnAuthenticationController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WebauthnCredentialsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["WebauthnCredentialsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/signup/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnSignupController_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/signup/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnSignupController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/step-up/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnStepUpController_options"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webauthn/step-up/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WebauthnStepUpController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BankController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/choice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BankController_choose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["BankController_remove"];
        options?: never;
        head?: never;
        patch: operations["BankController_update"];
        trace?: never;
    };
    "/banks/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BankController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountController_list"];
        put?: never;
        post: operations["AccountController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountController_chart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AccountController_balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AccountController_remove"];
        options?: never;
        head?: never;
        patch: operations["AccountController_update"];
        trace?: never;
    };
    "/accounts/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AccountController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reference-data/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReferenceDataController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reference-data/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReferenceDataController_paymentMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportController_list"];
        put?: never;
        post: operations["ReportController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportController_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportController_distribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ReportController_remove"];
        options?: never;
        head?: never;
        patch: operations["ReportController_update"];
        trace?: never;
    };
    "/reports/batch/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReportBatchController_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            status: string;
        };
        CsrfTokenResponseDto: {
            csrfToken: string;
        };
        RegisterDto: {
            email: string;
            country: string;
            /** @enum {string} */
            locale?: "en" | "fr";
        };
        MessageResponseDto: {
            message: string;
        };
        UpdateProfileDto: {
            email: string;
        };
        UpdateLocaleDto: {
            /** @enum {string} */
            locale: "en" | "fr";
        };
        ConfirmEmailChangeDto: {
            key: string;
        };
        CurrentMemberDto: {
            /** @enum {string} */
            locale: "en" | "fr";
            email: string;
        };
        SchedulerDto: {
            /** @enum {string} */
            frequencyUnit: "day" | "week" | "month" | "year";
            id: string;
            accountId: string;
            transferAccountId: string | null;
            categoryId: string | null;
            paymentMethodId: string;
            thirdParty: string;
            debit: number | null;
            credit: number | null;
            valueDate: string;
            reconciled: boolean;
            notes: string;
            limitDate: string | null;
            frequencyValue: number;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SchedulerListDto: {
            items: components["schemas"]["SchedulerDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateSchedulerDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            type: "debit" | "credit";
            thirdParty: string;
            amount: number;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            paymentMethodId: string;
            /** Format: uuid */
            transferAccountId?: string;
            valueDate: string;
            notes?: string;
            reconciled?: boolean;
            limitDate?: string;
            /** @enum {string} */
            frequencyUnit?: "day" | "week" | "month" | "year";
            frequencyValue: number;
            active?: boolean;
        };
        SchedulerSavedResponseDto: {
            message: string;
            scheduler: components["schemas"]["SchedulerDto"];
        };
        UpdateSchedulerDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            type: "debit" | "credit";
            thirdParty: string;
            amount: number;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            paymentMethodId: string;
            /** Format: uuid */
            transferAccountId?: string;
            valueDate: string;
            notes?: string;
            reconciled?: boolean;
            limitDate?: string;
            /** @enum {string} */
            frequencyUnit?: "day" | "week" | "month" | "year";
            frequencyValue: number;
            active?: boolean;
        };
        BatchIdsDto: {
            ids: string[];
        };
        SchedulerBatchDeleteResponseDto: {
            message: string;
            deletedCount: number;
        };
        OperationDto: {
            id: string;
            accountId: string;
            schedulerId: string | null;
            transferOperationId: string | null;
            transferAccountId: string | null;
            categoryId: string | null;
            paymentMethodId: string;
            thirdParty: string;
            debit: number | null;
            credit: number | null;
            valueDate: string;
            reconciled: boolean;
            notes: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OperationListDto: {
            items: components["schemas"]["OperationDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateOperationDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            type: "debit" | "credit";
            thirdParty: string;
            amount: number;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            paymentMethodId: string;
            /** Format: uuid */
            transferAccountId?: string;
            valueDate?: string;
            notes?: string;
            reconciled?: boolean;
        };
        OperationSavedResponseDto: {
            message: string;
            operation: components["schemas"]["OperationDto"];
        };
        UpdateOperationDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            type: "debit" | "credit";
            thirdParty: string;
            amount: number;
            /** Format: uuid */
            categoryId?: string;
            /** Format: uuid */
            paymentMethodId: string;
            /** Format: uuid */
            transferAccountId?: string;
            valueDate: string;
            notes?: string;
            reconciled?: boolean;
        };
        BatchDeleteResponseDto: {
            message: string;
            deletedCount: number;
        };
        BatchReconcileResponseDto: {
            message: string;
            reconciledCount: number;
        };
        AmountComparatorDto: {
            /** @enum {string} */
            operator: "gt" | "gte" | "lt" | "lte" | "eq";
            value: number;
        };
        SearchOperationsDto: {
            /** Format: uuid */
            accountId: string;
            /** @enum {string} */
            type?: "debit" | "credit";
            thirdParty?: string;
            categoryIds?: string[];
            paymentMethodIds?: string[];
            amountComparators?: components["schemas"]["AmountComparatorDto"][];
            dateFrom?: string;
            dateTo?: string;
            notes?: string;
            reconciled?: boolean;
        };
        SearchCriteriaDto: {
            /** @enum {string} */
            type?: "debit" | "credit";
            thirdParty?: string;
            categoryIds?: string[];
            paymentMethodIds?: string[];
            amountComparators?: components["schemas"]["AmountComparatorDto"][];
            dateFrom?: string;
            dateTo?: string;
            notes?: string;
            reconciled?: boolean;
        };
        OperationSearchRecallDto: {
            items: components["schemas"]["OperationDto"][];
            total: number;
            page: number;
            pageSize: number;
            criteria: components["schemas"]["SearchCriteriaDto"];
            active: boolean;
        };
        ThirdPartySuggestionDto: {
            thirdParty: string;
            categoryId: string | null;
        };
        VerifyRegistrationDto: {
            response: Record<string, never>;
            deviceName?: string;
        };
        VerifyAuthenticationDto: {
            response: Record<string, never>;
        };
        WebauthnCredentialSummaryDto: {
            id: string;
            deviceName: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string | null;
        };
        SignupOptionsDto: {
            key: string;
        };
        BankDto: {
            id: string;
            memberId: string;
            name: string;
            closed: boolean;
            deleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ChooseBankDto: {
            /** Format: uuid */
            bankId?: string;
            name?: string;
        };
        ChooseBankResponseDto: {
            id: string;
            name: string;
            created: boolean;
        };
        UpdateBankDto: {
            name: string;
        };
        AccountWithBalanceDto: {
            balance: number;
            reconciledBalance: number;
            id: string;
            bankId: string;
            name: string;
            currency: string;
            closed: boolean;
            deleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AxisBoundsDto: {
            min: number;
            max: number;
        };
        ChartPointDto: {
            period: string;
            value: number;
        };
        AccountChartDto: {
            currency: string;
            axisBounds: components["schemas"]["AxisBoundsDto"] | null;
            points: components["schemas"]["ChartPointDto"][];
        };
        AccountBalanceDto: {
            balance: number;
            reconciledBalance: number;
        };
        CreateAccountDto: {
            /** Format: uuid */
            bankId: string;
            name: string;
            /** @enum {string} */
            currency: "AED" | "AFN" | "ALL" | "AMD" | "ANG" | "AOA" | "ARS" | "AUD" | "AWG" | "AZN" | "BAM" | "BBD" | "BDT" | "BGN" | "BHD" | "BIF" | "BMD" | "BND" | "BOB" | "BRL" | "BSD" | "BTN" | "BWP" | "BYN" | "BZD" | "CAD" | "CDF" | "CHF" | "CLP" | "CNY" | "COP" | "CRC" | "CUC" | "CUP" | "CVE" | "CZK" | "DJF" | "DKK" | "DOP" | "DZD" | "EGP" | "ERN" | "ETB" | "EUR" | "FJD" | "FKP" | "GBP" | "GEL" | "GHS" | "GIP" | "GMD" | "GNF" | "GTQ" | "GYD" | "HKD" | "HNL" | "HRK" | "HTG" | "HUF" | "IDR" | "ILS" | "INR" | "IQD" | "IRR" | "ISK" | "JMD" | "JOD" | "JPY" | "KES" | "KGS" | "KHR" | "KMF" | "KPW" | "KRW" | "KWD" | "KYD" | "KZT" | "LAK" | "LBP" | "LKR" | "LRD" | "LSL" | "LYD" | "MAD" | "MDL" | "MGA" | "MKD" | "MMK" | "MNT" | "MOP" | "MRU" | "MUR" | "MVR" | "MWK" | "MXN" | "MYR" | "MZN" | "NAD" | "NGN" | "NIO" | "NOK" | "NPR" | "NZD" | "OMR" | "PAB" | "PEN" | "PGK" | "PHP" | "PKR" | "PLN" | "PYG" | "QAR" | "RON" | "RSD" | "RUB" | "RWF" | "SAR" | "SBD" | "SCR" | "SDG" | "SEK" | "SGD" | "SHP" | "SLE" | "SLL" | "SOS" | "SRD" | "SSP" | "STN" | "SVC" | "SYP" | "SZL" | "THB" | "TJS" | "TMT" | "TND" | "TOP" | "TRY" | "TTD" | "TWD" | "TZS" | "UAH" | "UGX" | "USD" | "UYU" | "UZS" | "VES" | "VND" | "VUV" | "WST" | "XAF" | "XCD" | "XCG" | "XDR" | "XOF" | "XPF" | "XSU" | "YER" | "ZAR" | "ZMW" | "ZWG" | "ZWL";
            initialBalance?: number;
        };
        AccountDto: {
            id: string;
            bankId: string;
            name: string;
            currency: string;
            closed: boolean;
            deleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AccountSavedResponseDto: {
            message: string;
            account: components["schemas"]["AccountDto"];
        };
        UpdateAccountDto: {
            name: string;
            /** Format: uuid */
            bankId: string;
            /** @enum {string} */
            currency: "AED" | "AFN" | "ALL" | "AMD" | "ANG" | "AOA" | "ARS" | "AUD" | "AWG" | "AZN" | "BAM" | "BBD" | "BDT" | "BGN" | "BHD" | "BIF" | "BMD" | "BND" | "BOB" | "BRL" | "BSD" | "BTN" | "BWP" | "BYN" | "BZD" | "CAD" | "CDF" | "CHF" | "CLP" | "CNY" | "COP" | "CRC" | "CUC" | "CUP" | "CVE" | "CZK" | "DJF" | "DKK" | "DOP" | "DZD" | "EGP" | "ERN" | "ETB" | "EUR" | "FJD" | "FKP" | "GBP" | "GEL" | "GHS" | "GIP" | "GMD" | "GNF" | "GTQ" | "GYD" | "HKD" | "HNL" | "HRK" | "HTG" | "HUF" | "IDR" | "ILS" | "INR" | "IQD" | "IRR" | "ISK" | "JMD" | "JOD" | "JPY" | "KES" | "KGS" | "KHR" | "KMF" | "KPW" | "KRW" | "KWD" | "KYD" | "KZT" | "LAK" | "LBP" | "LKR" | "LRD" | "LSL" | "LYD" | "MAD" | "MDL" | "MGA" | "MKD" | "MMK" | "MNT" | "MOP" | "MRU" | "MUR" | "MVR" | "MWK" | "MXN" | "MYR" | "MZN" | "NAD" | "NGN" | "NIO" | "NOK" | "NPR" | "NZD" | "OMR" | "PAB" | "PEN" | "PGK" | "PHP" | "PKR" | "PLN" | "PYG" | "QAR" | "RON" | "RSD" | "RUB" | "RWF" | "SAR" | "SBD" | "SCR" | "SDG" | "SEK" | "SGD" | "SHP" | "SLE" | "SLL" | "SOS" | "SRD" | "SSP" | "STN" | "SVC" | "SYP" | "SZL" | "THB" | "TJS" | "TMT" | "TND" | "TOP" | "TRY" | "TTD" | "TWD" | "TZS" | "UAH" | "UGX" | "USD" | "UYU" | "UZS" | "VES" | "VND" | "VUV" | "WST" | "XAF" | "XCD" | "XCG" | "XDR" | "XOF" | "XPF" | "XSU" | "YER" | "ZAR" | "ZMW" | "ZWG" | "ZWL";
        };
        CategoryDto: {
            /** @enum {string} */
            type: "debit" | "credit";
            id: string;
            parentId: string | null;
            name: string;
        };
        PaymentMethodDto: {
            /** @enum {string|null} */
            type: "debit" | "credit" | null;
            id: string;
            name: string;
        };
        ReportDto: {
            /** @enum {string} */
            type: "sum" | "average" | "distribution";
            /** @enum {string} */
            periodGrouping: "month" | "quarter" | "year" | "all";
            /** @enum {string|null} */
            dataGrouping: "category" | "third_party" | "payment_method" | null;
            id: string;
            memberId: string;
            title: string;
            homepage: boolean;
            valueDateStart: string | null;
            valueDateEnd: string | null;
            thirdParties: string | null;
            reconciledOnly: boolean | null;
            significantResultsNumber: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            accountIds: string[];
            categoryIds: string[];
        };
        ReportSeriesEntryDto: {
            currency: string;
            credit: components["schemas"]["ChartPointDto"][];
            debit: components["schemas"]["ChartPointDto"][];
        };
        ReportSeriesDto: {
            hidden: boolean;
            axisBounds: components["schemas"]["AxisBoundsDto"] | null;
            series: components["schemas"]["ReportSeriesEntryDto"][];
        };
        ReportDistributionLabelSeriesDto: {
            label: string | null;
            points: components["schemas"]["ChartPointDto"][];
        };
        ReportDistributionSeriesDto: {
            currency: string;
            debit: components["schemas"]["ReportDistributionLabelSeriesDto"][];
            credit: components["schemas"]["ReportDistributionLabelSeriesDto"][];
        };
        ReportDistributionDto: {
            hidden: boolean;
            series: components["schemas"]["ReportDistributionSeriesDto"][];
        };
        CreateReportDto: {
            /** @enum {string} */
            type: "sum" | "average" | "distribution";
            title: string;
            homepage?: boolean;
            valueDateStart?: string;
            valueDateEnd?: string;
            thirdParties?: string;
            accountIds?: string[];
            reconciledOnly?: boolean;
            categoryIds?: string[];
            /** @enum {string} */
            periodGrouping: "month" | "quarter" | "year" | "all";
            /** @enum {string} */
            dataGrouping?: "category" | "third_party" | "payment_method";
            significantResultsNumber?: number;
        };
        ReportSavedResponseDto: {
            message: string;
            report: components["schemas"]["ReportDto"];
        };
        UpdateReportDto: {
            /** @enum {string} */
            type: "sum" | "average" | "distribution";
            title: string;
            homepage?: boolean;
            valueDateStart?: string;
            valueDateEnd?: string;
            thirdParties?: string;
            accountIds?: string[];
            reconciledOnly?: boolean;
            categoryIds?: string[];
            /** @enum {string} */
            periodGrouping: "month" | "quarter" | "year" | "all";
            /** @enum {string} */
            dataGrouping?: "category" | "third_party" | "payment_method";
            significantResultsNumber?: number;
        };
        ReportBatchDeleteResponseDto: {
            message: string;
            deletedCount: number;
        };
        SeriesHomepageReportDto: {
            /** @enum {string} */
            kind: "series";
            id: string;
            title: string;
            series: components["schemas"]["ReportSeriesDto"];
        };
        DistributionHomepageReportDto: {
            /** @enum {string} */
            kind: "distribution";
            id: string;
            title: string;
            distribution: components["schemas"]["ReportDistributionDto"];
        };
        TotalBalanceDto: {
            currency: string;
            amount: number;
            reconciledAmount: number;
        };
        DashboardIndicatorDto: {
            amount: number;
            currency: string;
            valueDate: string;
            thirdParty: string;
        };
        SynthesisChartSeriesDto: {
            currency: string;
            points: components["schemas"]["ChartPointDto"][];
        };
        SynthesisChartDto: {
            hidden: boolean;
            axisBounds: components["schemas"]["AxisBoundsDto"] | null;
            series: components["schemas"]["SynthesisChartSeriesDto"][];
        };
        AccountsOverviewAccountDto: {
            id: string;
            name: string;
            currency: string;
            balance: number;
            reconciledBalance: number;
            history: number[];
        };
        AccountsOverviewBankDto: {
            id: string;
            name: string;
            accounts: components["schemas"]["AccountsOverviewAccountDto"][];
        };
        DashboardResponseDto: {
            /** @enum {string|null} */
            onboarding: "no-bank" | "no-account" | null;
            homepageReports: (components["schemas"]["SeriesHomepageReportDto"] | components["schemas"]["DistributionHomepageReportDto"])[];
            totalBalances: components["schemas"]["TotalBalanceDto"][];
            lastBiggestIncome: components["schemas"]["DashboardIndicatorDto"] | null;
            lastBiggestExpense: components["schemas"]["DashboardIndicatorDto"] | null;
            synthesisChart: components["schemas"]["SynthesisChartDto"];
            accountsOverview: components["schemas"]["AccountsOverviewBankDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    CsrfTokenController_csrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponseDto"];
                };
            };
        };
    };
    RegistrationController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    ProfileController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    ProfileController_updateLocale: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocaleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    ProfileController_confirmEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChangeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    SignOutController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    CurrentSessionController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentMemberDto"];
                };
            };
        };
    };
    SchedulerController_list: {
        parameters: {
            query: {
                accountId: string;
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerListDto"];
                };
            };
        };
    };
    SchedulerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSchedulerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerSavedResponseDto"];
                };
            };
        };
    };
    SchedulerController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    SchedulerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSchedulerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    SchedulerBatchController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIdsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerBatchDeleteResponseDto"];
                };
            };
        };
    };
    OperationController_list: {
        parameters: {
            query: {
                accountId: string;
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationListDto"];
                };
            };
        };
    };
    OperationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOperationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationSavedResponseDto"];
                };
            };
        };
    };
    OperationController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOperationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    OperationBatchController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIdsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDeleteResponseDto"];
                };
            };
        };
    };
    OperationBatchController_reconcile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIdsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchReconcileResponseDto"];
                };
            };
        };
    };
    OperationSearchController_recall: {
        parameters: {
            query: {
                accountId: string;
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationSearchRecallDto"];
                };
            };
        };
    };
    OperationSearchController_run: {
        parameters: {
            query?: {
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchOperationsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationListDto"];
                };
            };
        };
    };
    OperationSearchController_clear: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    OperationAutocompleteController_search: {
        parameters: {
            query: {
                q: string;
                type?: "debit" | "credit";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThirdPartySuggestionDto"][];
                };
            };
        };
    };
    WebauthnRegistrationController_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    WebauthnRegistrationController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRegistrationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    WebauthnAuthenticationController_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    WebauthnAuthenticationController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyAuthenticationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    WebauthnCredentialsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebauthnCredentialSummaryDto"][];
                };
            };
        };
    };
    WebauthnCredentialsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    WebauthnSignupController_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupOptionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    WebauthnSignupController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRegistrationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    WebauthnStepUpController_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    WebauthnStepUpController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyAuthenticationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    BankController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankDto"][];
                };
            };
        };
    };
    BankController_choose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChooseBankDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChooseBankResponseDto"];
                };
            };
        };
    };
    BankController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    BankController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBankDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    BankController_close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    AccountController_list: {
        parameters: {
            query?: {
                bankId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalanceDto"][];
                };
            };
        };
    };
    AccountController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSavedResponseDto"];
                };
            };
        };
    };
    AccountController_chart: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountChartDto"];
                };
            };
        };
    };
    AccountController_balance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountBalanceDto"];
                };
            };
        };
    };
    AccountController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    AccountController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    AccountController_close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    ReferenceDataController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
        };
    };
    ReferenceDataController_paymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodDto"][];
                };
            };
        };
    };
    ReportController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDto"][];
                };
            };
        };
    };
    ReportController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSavedResponseDto"];
                };
            };
        };
    };
    ReportController_series: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSeriesDto"];
                };
            };
        };
    };
    ReportController_distribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDistributionDto"];
                };
            };
        };
    };
    ReportController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    ReportController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReportDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponseDto"];
                };
            };
        };
    };
    ReportBatchController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIdsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportBatchDeleteResponseDto"];
                };
            };
        };
    };
    DashboardController_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
        };
    };
}
