<?php echo $this->doctype(), "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle(), "\n" ?>
        <?php echo $this->headMeta(), "\n" ?>
        <?php echo $this->headLink(), "\n" ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/head.load.min.js"></script>
        <script type="text/javascript">
        head.js(
            "<?php echo $this->baseUrl; ?>/js/jquery-1.5.min.js",
            "<?php echo $this->baseUrl; ?>/js/Bagheera.js",
            "<?php echo $this->baseUrl; ?>/translate/list",
            function(){
                Bagheera.baseUrl = "<?php echo $this->baseUrl; ?>";
                Bagheera.init();
            }
        );
        </script>
    </head>
    <body>
        <div id="top">
            <h1>Bagheera</h1>

            <?php if (null !== $this->currentUser) { ?>
            <p class="logout"><?php echo $this->link('logout', $this->translate('userLogoutLink')) ?></p>

            <ul id="menu">
                <li><?php echo $this->link('home', $this->translate('menuHome')) ?></li>
                <li><?php echo $this->link('profile', $this->translate('menuProfile')) ?></li>
                <!-- <li><?php //echo $this->link('sharesList', $this->translate('menuShares')) ?></li> -->
                <!-- <li><?php //echo $this->link('reportsList', $this->translate('menuReports')) ?></li> -->
                <?php if ($this->currentUser->getIsAdmin()) { ?>
                <li><?php echo $this->link('usersList', $this->translate('menuAdminUsers')) ?></li>
                <!-- <li><?php //echo $this->link('categoriesList', $this->translate('menuAdminCategories')) ?></li> -->
                <!-- <li><?php //echo $this->link('paymentMethodsList', $this->translate('menuAdminPaymentMethods')) ?></li> -->
                <?php } ?>
            </ul>
            <?php } ?>

            <?php if ($this->selectedAccount) { ?>
            <div id="accountInfo">
                <strong><?php echo $this->selectedAccount->getBank()->getName() . ' - ' . $this->selectedAccount->getName() ?></strong><br/>
                <?php
                echo $this->translate('balance') . ' : <strong class="' . ($this->selectedAccount->getBalance() < 0 ? 'negative' : 'positive') . '">' . sprintf('%.2f', abs($this->selectedAccount->getBalance())) . '</strong><br/>';
                echo $this->translate('reconciledBalance') . ' : <strong class="' . ($this->selectedAccount->getBalance(true) < 0 ? 'negative' : 'positive') . '">' . sprintf('%.2f', abs($this->selectedAccount->getBalance(true))) . '</strong>';
                ?>
            </div>
            <?php } ?>
        </div>

        <div id="content">
            <?php
            if (!empty($this->messages)) {
                echo '<ul class="info">', "\n";
                foreach ($this->messages as $message) {
                    echo '<li>', $this->translate($message), '</li>', "\n";
                }
                echo '</ul>', "\n";
                echo '<div class="clear"></div>';
            }

            echo $this->layout()->content, "\n";
            ?>
            <div class="clear"></div>
        </div>

        <div id="footer">
            <p id="copyright">Bagheera © 2011</p>
        </div>

        <?php echo $this->headScript(), "\n" ?>
    </body>
</html>
