<?php echo $this->doctype(), "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle(), "\n" ?>
        <?php echo $this->headMeta(), "\n" ?>
        <?php echo $this->headLink(), "\n" ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/head.load.min.js"></script>
        <script type="text/javascript">
        head.js(
            "<?php echo $this->baseUrl; ?>/js/jquery-1.5.min.js",
            "<?php echo $this->baseUrl; ?>/js/Bagheera.js",
            function(){
                Bagheera.baseUrl = "<?php echo $this->baseUrl; ?>";
                Bagheera.init();
            }
        );
        </script>
    </head>
    <body>
        <div id="sidebar">
            <p><?php echo $this->link('logout', $this->translate('logoutLink')) ?><br/><br/></p>

            <ul id="menu">
                <li><?php echo $this->link('home', $this->translate('menuHome')) ?></li>
                <li>
                    <?php echo $this->link('myInfos', $this->translate('menuMyInfos')) ?>
                    <ul>
                        <li><?php echo $this->link('profile', $this->translate('menuProfile')) ?></li>
                        <li><?php echo $this->link('accounts', $this->translate('menuAccounts')) ?></li>
                        <li><?php echo $this->link('shares', $this->translate('menuShares')) ?></li>
                    </ul>
                </li>
                <li>
                    <?php echo $this->link('scheduler', $this->translate('menuScheduler')) ?>
                    <ul>
                        <li><?php echo $this->link('schedulerList', $this->translate('menuSchedulerList')) ?></li>
                        <li><?php echo $this->link('schedulerDueTransactions', $this->translate('menuSchedulerDueTransactions')) ?></li>
                    </ul>
                </li>
                <li><?php echo $this->link('reports', $this->translate('menuReports')) ?></li>
                <li>
                    <?php echo $this->link('admin', $this->translate('menuAdmin')) ?>
                    <ul>
                        <li><?php echo $this->link('users', $this->translate('menuUsers')) ?></li>
                        <li><?php echo $this->link('categories', $this->translate('menuCategories')) ?></li>
                        <li><?php echo $this->link('paymentMethods', $this->translate('menuPaymentMethods')) ?></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div id="content">
            <?php
            if (!empty($this->messages)) {
                echo '<ul>', "\n";
                foreach ($this->messages as $message) {
                    echo '<li>', $this->translate($message), '</li>', "\n";
                }
                echo '</ul>', "\n";
            }

            echo $this->layout()->content, "\n";
            ?>
        </div>

        <?php echo $this->headScript(), "\n" ?>
    </body>
</html>
